name: Build Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Update Package.json Version
        run: |
          sed -i "s/\"version\": \"[0-9.]*\"/\"version\": \"${{ env.VERSION }}\"/g" package.json
          cat package.json
      
      - name: Create Package
        run: |
          mkdir -p build
          zip -r build/jp.21csx.face-anim-optimizer-${{ env.VERSION }}.zip . -x "*.git*" "build/*" ".github/*" "vpm.json" "index.html" "favicon.png" ".nojekyll"
      
      - name: Calculate Checksum
        run: |
          CHECKSUM=$(sha256sum build/jp.21csx.face-anim-optimizer-${{ env.VERSION }}.zip | awk '{ print $1 }')
          echo "CHECKSUM=${CHECKSUM^^}" >> $GITHUB_ENV
          echo "Checksum: ${CHECKSUM^^}"
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/jp.21csx.face-anim-optimizer-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
